service: serverless-awslambda-github-cicd-nodejs

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber 